- name: Install AppDB Databases
  hosts: all
  gather_facts: yes
  vars:
    om_nodes: 'True'
    Enable_backup: 'True'
    Cluster_Nodes: 'false'
    group_name: tag_deployment_ops_manager_dev
    aws_region: cn-northwest-1
    mongod_port: 27000
    backing_DB_port: 28000
    database_creds_name: MongoDB-Creds
    MongoKeySecretName: MongoKey
    tag_value: "fqdn"
  pre_tasks:
    - name: Fetch the Secrets from the aws Secret manager
      set_fact:
        mongo_key: "{{ lookup('amazon.aws.aws_secret', MongoKeySecretName, region=aws_region)}}"
        mongodb_password: "{{ (lookup('amazon.aws.aws_secret', database_creds_name, region=aws_region) | from_json).Password }}"
        mongodb_username: "{{ (lookup('amazon.aws.aws_secret', database_creds_name, region=aws_region) | from_json).Username }}"
  roles:
    - os-changes
    - certs
    - databases
    - metadatadb
    - name: Run Automation role only on localhost
      role: opsmgr
      when:  inventory_hostname != groups['{{ group_name }}'][2] 